trigger:
  branches:
    include:
      - master
      - dev
      - qa
  paths:
    include:
      - backend/*
    exclude:
      - frontend/*
      - infrastructure/*
  batch: true

pr:
  branches:
    include:
      - master
      - dev
      - qa
  paths:
    include:
      - backend/*
    exclude:
      - frontend/*
      - infrastructure/*

pool: Default

variables:
  buildConfiguration: "Release"
  dotnetVersion: "8.0.x"
  mainProjectLocation: "backend/src/UniversityManagementSystem.API/UniversityManagementSystem.API.csproj"
  testProjectLocation: "backend/test/UniversityManagementSystem.Test/UniversityManagementSystem.Test.csproj"
  azureSubscription: "azure-connect"
  artifactName: "myWebsite" # Name of the artifact in Azure DevOps
  zipFile: "UniversityManagementSystem.API.zip" # The artifact zip file name

stages:
  - stage: "Build"
    displayName: "Build Stage"
    jobs:
      - job: "BuildApp"
        displayName: "Build ASP.NET Core 8 Application"
        steps:
          # Install the specified .NET SDK version
          - task: UseDotNet@2
            displayName: "Install .NET Core SDK"
            inputs:
              version: 8.x
              performMultiLevelLookup: true
              includePreviewVersions: true # Required for preview versions

            # Restore the project
          # - task: DotNetCoreCLI@2
          #   displayName: "Restore Dependencies"
          #   inputs:
          #     project: $(mainProjectLocation)
          #     command: "restore"
          #     feedsToUse: "select"
          #     vstsFeed: "my-vsts-feed" # A series of numbers and letters

          # Build the project
          - task: DotNetCoreCLI@2
            displayName: "dotnet build $(buildConfiguration)"
            inputs:
              command: "build"
              project: $(mainProjectLocation)
              arguments: "--configuration $(buildConfiguration)"

          # Test Code Run the project
          - task: DotNetCoreCLI@2
            displayName: "run test code"
            inputs:
              command: test
              project: $(testProjectLocation)
              projects: "**/*Tests/*.csproj"
              arguments: "--configuration $(buildConfiguration)"

          - task: DotNetCoreCLI@2
            displayName: "publish project"
            inputs:
              command: publish
              publishWebProjects: True
              project: $(mainProjectLocation)
              arguments: "--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)"
              zipAfterPublish: True

            # this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
          - task: PublishPipelineArtifact@1
            displayName: "genreate artifact file"
            inputs:
              targetPath: "$(Build.ArtifactStagingDirectory)"
              artifactName: "myWebsite"

  - stage: "Dev"
    displayName: "Deploy to the dev environment"
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'dev'))
    jobs:
      # ✅ Download Artifact
      - task: DownloadBuildArtifacts@0
        displayName: "Download Artifact"
        inputs:
          buildType: "current"
          artifactName: "$(artifactName)"
          downloadPath: "$(Pipeline.Workspace)"

        # ✅ Deploy ZIP to Azure App Service
      - task: AzureWebApp@1
        displayName: "Deploy to Azure App Service"
        inputs:
          azureSubscription: "$(azureSubscription)"
          appName: "university-management-system-dev"
          package: "$(Pipeline.Workspace)/$(artifactName)/$(zipFile)"
