trigger:
  branches:
    include:
      - master
      - dev
      - qa
  paths:
    include:
      - backend/*
    exclude:
      - frontend/*
      - infrastructure/*
  batch: true

pr:
  branches:
    include:
      - master
      - dev
      - qa
  paths:
    include:
      - backend/*
    exclude:
      - frontend/*
      - infrastructure/*

pool: Default

variables:
  buildConfiguration: "Release"
  dotnetVersion: "8.0.x"
  mainProjectLocation: "backend/src/UniversityManagementSystem.API/UniversityManagementSystem.API.csproj"
  testProjectLocation: "backend/test/UniversityManagementSystem.Test/UniversityManagementSystem.Test.csproj"

stages:
  - stage: "Build"
    displayName: "Build Stage"
    jobs:
      - job: "BuildApp"
        displayName: "Build ASP.NET Core 8 Application"
        steps:
          # Install the specified .NET SDK version
          - task: UseDotNet@2
            displayName: "Install .NET Core SDK"
            inputs:
              version: 8.x
              performMultiLevelLookup: true
              includePreviewVersions: true # Required for preview versions

            # Restore the project
          - task: DotNetCoreCLI@2
            displayName: "Restore Dependencies"
            inputs:
              project: $(mainProjectLocation)
              command: "restore"
              feedsToUse: "select"
              vstsFeed: "my-vsts-feed" # A series of numbers and letters

            # Build the project
          - task: DotNetCoreCLI@2
            displayName: "dotnet build $(buildConfiguration)"
            inputs:
              command: "build"
              project: $(mainProjectLocation)
              arguments: "--configuration $(buildConfiguration) --no-restore"

          # Test Code Run the project
          - task: DotNetCoreCLI@2
            inputs:
              command: test
              project: $(testProjectLocation)
              projects: "**/*Tests/*.csproj"
              arguments: "--configuration $(buildConfiguration)"

          - task: DotNetCoreCLI@2
            inputs:
              command: publish
              publishWebProjects: True
              project: $(mainProjectLocation)
              arguments: "--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)"
              zipAfterPublish: True

            # this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: "$(Build.ArtifactStagingDirectory)"
              artifactName: "myWebsite"
